### ISSUE TITLE
Consider switch to PhpCsFixer\Config for docheaders

### ISSUE THREAD

**Issue by basz** [prooph/php-cs-fixer-config#4]
Just encountered this trick (of the day (tm)) from https://localheinz.com/blog/2018/05/06/cost-and-value-of-docblocks/

```
<?php

$header = <<<EOF
Copyright (c) 2017 Andreas Möller

For the full copyright and license information, please view
the LICENSE file that was distributed with this source code.

@see https://github.com/localheinz/test-util
EOF;

$config = PhpCsFixer\Config::create()->setRules([
    'header_comment' => [
        'commentType' => 'PHPDoc',
        'header' => $header,
        'location' => 'after_declare_strict',
        'separate' => 'both',
    ],
]);

```

We would be able to remove all traces of 'malukenho/docheader'. 

I just did it here https://github.com/plhw/hf-cs-fixer-config/blob/master/src/Config.php#L132-L159; works great

**Comment by sandrokeil** [comment]
Sounds reasonable and can fix wrong docheader automatically. :+1:

**Comment by basz** [comment]
Yes, especially the useless commit dance we have to do every new year. I’ll create the nessesarry PR’s before new years eve...

**Comment by basz** [comment]
see #6
